[neovim]
src.git = "https://github.com/jordycoding/neovim-lua.git"
fetch.github = "jordycoding/neovim-lua"

[dotfiles]
src.git = "https://github.com/jordycoding/Dotfiles-Xps.git"
fetch.github = "jordycoding/Dotfiles-Xps"

[kittycatppuccin]
src.git = "https://github.com/catppuccin/kitty.git"
fetch.github = "catppuccin/kitty"

[alacrittycatppuccin]
src.git = "https://github.com/catppuccin/alacritty.git"
fetch.github = "catppuccin/alacritty"

[dnsblacklist]
src.manual = "2024.0417.0102.50"
fetch.url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/7c587c2/dnsmasq/pro.plus.txt"
