# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "nix/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/7522-A7AF";
      fsType = "vfat";
    };

  fileSystems."/mnt/Media/Anime" =
    {
      device = "media/Anime";
      fsType = "zfs";
    };

  fileSystems."/mnt/Media/Movies" =
    {
      device = "media/Movies";
      fsType = "zfs";
    };

  fileSystems."/mnt/Media/Series" =
    {
      device = "media/Series";
      fsType = "zfs";
    };

  fileSystems."/mnt/Ssd/Downloads" =
    {
      device = "ssd/Downloads";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "vault/Homes";
      fsType = "zfs";
    };

  fileSystems."/mnt/Vault/Data" = {
    device = "vault/Data";
    fsType = "zfs";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
