# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacrittycatppuccin = {
    pname = "alacrittycatppuccin";
    version = "94800165c13998b600a9da9d29c330de9f28618e";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "94800165c13998b600a9da9d29c330de9f28618e";
      fetchSubmodules = false;
      sha256 = "sha256-Pi1Hicv3wPALGgqurdTzXEzJNx7vVh+8B9tlqhRpR2Y=";
    };
    date = "2024-04-09";
  };
  dnsblacklist = {
    pname = "dnsblacklist";
    version = "2024.0417.0102.50";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/7c587c2/dnsmasq/pro.plus.txt";
      sha256 = "sha256-URg0ye2IUzq8dLgJiHRG6rCvDvtBZPQ5VuNK1OPsSgY=";
    };
  };
  dotfiles = {
    pname = "dotfiles";
    version = "74d70eba06c19bf8ae9c956c35cb108092cce86c";
    src = fetchFromGitHub {
      owner = "jordycoding";
      repo = "Dotfiles-Xps";
      rev = "74d70eba06c19bf8ae9c956c35cb108092cce86c";
      fetchSubmodules = false;
      sha256 = "sha256-4TUqSHTstDnTzu6PhFPWebnY8vWxhSM2tUNE4/xMUqo=";
    };
    date = "2024-03-09";
  };
  kittycatppuccin = {
    pname = "kittycatppuccin";
    version = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
      fetchSubmodules = false;
      sha256 = "sha256-mRFa+40fuJCUrR1o4zMi7AlgjRtFmii4fNsQyD8hIjM=";
    };
    date = "2024-01-10";
  };
  neovim = {
    pname = "neovim";
    version = "a7b97eaa0cd8057a189ca801acbcfa4e308fa080";
    src = fetchFromGitHub {
      owner = "jordycoding";
      repo = "neovim-lua";
      rev = "a7b97eaa0cd8057a189ca801acbcfa4e308fa080";
      fetchSubmodules = false;
      sha256 = "sha256-fRIENOp9BlLZ0kSEtCTIywHgt4CBXDCJXjYR21Dwy1k=";
    };
    date = "2024-04-21";
  };
}
