# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alacrittycatppuccin = {
    pname = "alacrittycatppuccin";
    version = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "f6cb5a5c2b404cdaceaff193b9c52317f62c62f7";
      fetchSubmodules = false;
      sha256 = "sha256-H8bouVCS46h0DgQ+oYY8JitahQDj0V9p2cOoD4cQX+Q=";
    };
    date = "2024-10-28";
  };
  dnsblacklist = {
    pname = "dnsblacklist";
    version = "2024.0417.0102.50";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/7c587c2/dnsmasq/pro.plus.txt";
      sha256 = "sha256-URg0ye2IUzq8dLgJiHRG6rCvDvtBZPQ5VuNK1OPsSgY=";
    };
  };
  dotfiles = {
    pname = "dotfiles";
    version = "74d70eba06c19bf8ae9c956c35cb108092cce86c";
    src = fetchFromGitHub {
      owner = "jordycoding";
      repo = "Dotfiles-Xps";
      rev = "74d70eba06c19bf8ae9c956c35cb108092cce86c";
      fetchSubmodules = false;
      sha256 = "sha256-4TUqSHTstDnTzu6PhFPWebnY8vWxhSM2tUNE4/xMUqo=";
    };
    date = "2024-03-09";
  };
  kittycatppuccin = {
    pname = "kittycatppuccin";
    version = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "b14e8385c827f2d41660b71c7fec1e92bdcf2676";
      fetchSubmodules = false;
      sha256 = "sha256-59ON7CzVgfZUo7F81qQZQ1r6kpcjR3OPvTl99gzDP8E=";
    };
    date = "2024-11-10";
  };
  neovim = {
    pname = "neovim";
    version = "963f3cdbfbfea81ba641ee9e0f7dcafe7487e44e";
    src = fetchFromGitHub {
      owner = "jordycoding";
      repo = "neovim-lua";
      rev = "963f3cdbfbfea81ba641ee9e0f7dcafe7487e44e";
      fetchSubmodules = false;
      sha256 = "sha256-IaV7a2FZuiMs4y2u/BxhZ8tgBpBFZ8zqUvMi/OVp+sw=";
    };
    date = "2025-03-16";
  };
  rpzblacklist = {
    pname = "rpzblacklist";
    version = "08d43168cd599589dff8c557b44f724e4b25725b";
    src = fetchFromGitHub {
      owner = "hagezi";
      repo = "dns-blocklists";
      rev = "08d43168cd599589dff8c557b44f724e4b25725b";
      fetchSubmodules = false;
      sha256 = "sha256-sqPyPynSUkXnC/O2oECjtUbftOAp8shORO4W25wj+Ps=";
    };
    date = "2025-03-16";
  };
}
