# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "uas" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a8c7340a-6bc6-46f1-8826-b6f3ba3e35bc";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/a8c7340a-6bc6-46f1-8826-b6f3ba3e35bc";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/a8c7340a-6bc6-46f1-8826-b6f3ba3e35bc";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/mnt/shared" =
    { device = "/dev/disk/by-uuid/a8c7340a-6bc6-46f1-8826-b6f3ba3e35bc";
      fsType = "btrfs";
      options = [ "subvol=@shared" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6549-0500";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/games" =
    { device = "/dev/disk/by-uuid/a8c7340a-6bc6-46f1-8826-b6f3ba3e35bc";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/mnt/games_sata" =
    { device = "/dev/disk/by-uuid/d13737a2-adcf-4397-97fb-56586dba4ac3";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
